services:
  postgres:
    image: postgres:16.3
    container_name: database-library
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: database-library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data: