services:
  database:
    image: postgres:16.3-alpine
    container_name: database-library
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: database-library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  database_data: